"""Initial schema

Revision ID: 24d7d3bc2893
Revises: 
Create Date: 2026-05-18 02:48:48.910582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '24d7d3bc2893'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if a table exists
    conn = op.get_bind()
    from sqlalchemy.engine import reflection
    inspector = reflection.Inspector.from_engine(conn)
    existing_tables = inspector.get_table_names()
    
    def table_exists(name: str) -> bool:
        return name in existing_tables
        
    def index_exists(table_name: str, index_name: str) -> bool:
        if not table_exists(table_name):
            return False
        indexes = inspector.get_indexes(table_name)
        return any(idx['name'] == index_name for idx in indexes)

    # 1. places
    if not table_exists('places'):
        op.create_table('places',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('google_place_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('user_ratings_total', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not index_exists('places', 'idx_places_location'):
        op.create_index('idx_places_location', 'places', ['location'], unique=False, postgresql_using='gist')
    if not index_exists('places', 'ix_places_google_place_id'):
        op.create_index(op.f('ix_places_google_place_id'), 'places', ['google_place_id'], unique=True)

    # 2. users
    if not table_exists('users'):
        op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not index_exists('users', 'ix_users_email'):
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # 3. incidents
    if not table_exists('incidents'):
        op.create_table('incidents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('type', sa.Enum('ACCIDENT', 'CLOSURE', 'HAZARD', 'TRAFFIC', 'WATERLOGGING', 'POTHOLE', 'STRAY_ANIMAL', 'POLICE_CHECK', 'EVENT', name='incidenttype'), nullable=False),
        sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
        sa.Column('reporter_id', sa.UUID(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('upvotes', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not index_exists('incidents', 'idx_incidents_location'):
        op.create_index('idx_incidents_location', 'incidents', ['location'], unique=False, postgresql_using='gist')

    # 4. pins
    if not table_exists('pins'):
        op.create_table('pins',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not index_exists('pins', 'idx_pins_location'):
        op.create_index('idx_pins_location', 'pins', ['location'], unique=False, postgresql_using='gist')

    # 5. reviews
    if not table_exists('reviews'):
        op.create_table('reviews',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('place_id', sa.UUID(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # 6. timeline
    if not table_exists('timeline'):
        op.create_table('timeline',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not index_exists('timeline', 'idx_timeline_location'):
        op.create_index('idx_timeline_location', 'timeline', ['location'], unique=False, postgresql_using='gist')

    # 7. user_lists
    if not table_exists('user_lists'):
        op.create_table('user_lists',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # 8. user_list_places
    if not table_exists('user_list_places'):
        op.create_table('user_list_places',
        sa.Column('list_id', sa.UUID(), nullable=False),
        sa.Column('place_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('list_id', 'place_id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_list_places')
    op.drop_table('user_lists')
    op.drop_index('idx_timeline_location', table_name='timeline', postgresql_using='gist')
    op.drop_table('timeline')
    op.drop_table('reviews')
    op.drop_index('idx_pins_location', table_name='pins', postgresql_using='gist')
    op.drop_table('pins')
    op.drop_index('idx_incidents_location', table_name='incidents', postgresql_using='gist')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_places_google_place_id'), table_name='places')
    op.drop_index('idx_places_location', table_name='places', postgresql_using='gist')
    op.drop_table('places')
    # ### end Alembic commands ###
